import { refs } from './js/refs';
// import './js/AuthenticationService';
import './js/trendsMovies';
import './js/searchMovies';
import './js/movieHelpers';
import './js/pagination';
import './js/preloader';
import { onTopBallon } from './js/component/btn-to-top';
import './js/openModal';
import './js/day-night';
import './js/teamModal';
import './js/set-to-watched';
import './js/ApiService';
